// Verifies the llms.txt index generated by pages/llms.txt.ts.
// llms.txt is a hierarchical Markdown index of every page on the site —
// see https://llmstxt.org. Each entry links to the page's raw .md alternate.
// Build copies the file to the bundle root so it's available at both
// /docs/llms.txt and /llms.txt (the second only matters in prod via the
// Cloudflare bundle layout, not via astro preview).
export {};

describe("Dolt docs — llms.txt", () => {
  let body: string;

  before(() => {
    cy.request("/llms.txt").then(res => {
      expect(res.status).to.eq(200);
      body = res.body as string;
    });
  });

  it("starts with the site title and a blockquote summary", () => {
    expect(body).to.match(/^# Dolt\n\n> /);
  });

  it("includes one H2 per top-level nav section, plus Community & Source", () => {
    // Spot-check a handful of section headings — most are driven by nav.ts;
    // Community & Source is appended as a standalone section in the generator.
    for (const h of [
      "## Introduction",
      "## Concepts",
      "## SQL Reference",
      "## CLI Reference",
      "## Architecture",
      "## Guides",
      "## Products",
      "## Other",
      "## Community & Source",
    ]) {
      expect(body).to.include(h);
    }
  });

  it("appends the Agentic Writes blog entry to the Introduction section", () => {
    // Non-doc entry the generator injects after the nav items in Introduction.
    expect(body).to.include("[Agentic Writes with Dolt]");
    expect(body).to.include("/blog/2026-06-04-agentic-writes/");
  });

  it("lists GitHub repos, the blog, and Discord under Community & Source", () => {
    for (const link of [
      "https://github.com/dolthub/dolt",
      "https://github.com/dolthub/go-mysql-server",
      "https://github.com/dolthub/doltgresql",
      "https://discord.com/invite/RFwfYpu",
    ]) {
      expect(body).to.include(link);
    }
  });

  it("links every docs page entry to a .md alternate", () => {
    // Doc-page entries always point at the .md alternate. External entries
    // (blog posts, GitHub, Discord) are allowed to be regular HTML URLs.
    const urls = [...body.matchAll(/\]\(([^)]+)\)/g)].map(m => m[1]);
    expect(urls.length).to.be.greaterThan(50);
    for (const url of urls) {
      if (!url.includes("/docs/")) continue;
      expect(url, `docs entry should link to a .md alternate: ${url}`).to.match(
        /\.md$/,
      );
    }
  });

  it("surfaces frontmatter descriptions where present", () => {
    // The What Is Dolt? page has a description; it should appear after the
    // colon in its llms.txt entry.
    expect(body).to.match(
      /\[What Is Dolt\?\]\([^)]+\.md\): What Dolt is, what sets it apart/,
    );
  });
});
