// Verifies the llms.txt index generated by pages/llms.txt.ts.
// llms.txt is a hierarchical Markdown index of every page on the site —
// see https://llmstxt.org. Each entry links to the page's raw .md alternate.
// Build copies the file to the bundle root so it's available at both
// /docs/llms.txt and /llms.txt (the second only matters in prod via the
// Cloudflare bundle layout, not via astro preview).
export {};

describe("Dolt docs — llms.txt", () => {
  let body: string;

  before(() => {
    cy.request("/llms.txt").then(res => {
      expect(res.status).to.eq(200);
      body = res.body as string;
    });
  });

  it("starts with the site title and a blockquote summary", () => {
    expect(body).to.match(/^# Dolt Documentation\n\n> /);
  });

  it("includes one H2 per top-level nav section", () => {
    // Spot-check a handful of section headings — full list is driven by nav.ts.
    for (const h of [
      "## Introduction",
      "## Concepts",
      "## SQL Reference",
      "## CLI Reference",
      "## Architecture",
      "## Guides",
      "## Products",
      "## Other",
    ]) {
      expect(body).to.include(h);
    }
  });

  it("links every entry to a .md URL", () => {
    // Pull every link target out and confirm they all end in .md.
    const urls = [...body.matchAll(/\]\(([^)]+)\)/g)].map(m => m[1]);
    expect(urls.length).to.be.greaterThan(50);
    for (const url of urls) {
      expect(url, `entry should link to a .md alternate: ${url}`).to.match(
        /\.md$/,
      );
    }
  });

  it("surfaces frontmatter descriptions where present", () => {
    // The What Is Dolt? page has a description as of this PR — it should
    // appear after the colon in its llms.txt entry.
    expect(body).to.match(
      /\[What Is Dolt\?\]\([^)]+\.md\): Introduction to Dolt/,
    );
  });
});
